### PR TITLE
Update base.html - change popover text

### PR DESCRIPTION
**Pull request by morchickit**
Changed text to explains the value better

### CODE REVIEW

**Comment by morchickit** [comment]
@brew - what's up with Travis here?

**Comment by brew** [comment]
Sometimes Travis tests fail where there's nothing really wrong. I re-ran it, and it passes. This is because we test against live data sources (we shouldn't, ideally), and the tests occasionally fail to pick them up.

**Comment by morchickit** [comment]
Ok, cool. Good to know :-) Merging it

**Comment by morchickit** [comment]
Yes, i noticed the capital. 

This number doesnt need to explain 'open' though, no?

To me, this number shows the amount of datasets that are open in a county, but in percentage

**Comment by brew** [comment]
We're not explaining the number, we're explaining the word 'open'.

**Pull request merged**
